# Not fully implemented yet. Please use with caution and veryify.

[esi]
user_agent = "wcmkts_backend/2.1dev, orthel.toralen@gmail.com, (https://github.com/OrthelT/wcmkts_backend)" #change this to reflect your app please.
compatibility_date = "2025-08-26"

[auth]
# esi_client_id, esi_secret_key, and refresh token should be set in .env file for local development. Use secure credential storage (github secrets) in production.
callback_url = "http://localhost:8000/callback"
token_file = "file:token.json"

[app]
name = "WinterCo Markets"
market_name = "4-HWWF"
environment = "development"  # "production" or "development"
log_level = "info"
binding = 'turso' # 'turso' or 'libsql' for database type

[db] # change this to reflect your database. You will need to also edit the database aliases in the .env file and in the .github/workflows/market-data-collection.yml file.
# sde_db_alias = "sde"
# sde_db_file = "sde.db"

# fitting_db_alias = "fitting"
# fitting_db_file = "wcfitting.db"

# production_database_alias = "wcmktprod"
# production_database_file = "wcmktprod.db"

# #development databases used when app.environment set "development"
# testing_database_alias = "wcmkttest"
# testing_database_file = "wcmkttest.db"

# testing_sde_alias = "sdetest"
# testing_sde_file = "sdetest.db"

# testing_fitting_alias = "wcfittingtest"
# testing_fitting_file = "wcfittingtest.db"

# North market (secondary production) database
north_database_alias = "wcmktnorth"
north_database_file = "wcmktnorth2.db"



#the alias for the file used to access .env credentials
#and the prefix for the local db file <alias>.db 
#(i.e. alias = wcfitting, file: wcfitting.db)

[production]
sde = "sde"
fittings = "wcfitting"
wcmkt = "wcmktprod"

[development]
sde = "sdetest"
fittings = "wcfittingtest"
wcmkt = "wcmkttest3"

[testing]
[testing.sde]
alias = "sdetest2"
file = "sdetest2.db"

[market_data]
primary_market_region_id = 10000003
secondary_market_region_id = 'None'
primary_market_system_id = 30000240
secondary_market_system_id = 'None'
primary_market_structure_id = 1035466617946
secondary_market_structure_id = 'None'

[google_sheets]
enabled = false
sheet_url = 'https://docs.google.com/spreadsheets/d/1RmNJB9Yz4lG6kKKitGQ0zDuPbOiSe0ywn4SbSKabdwc/edit?gid=0#gid=0'
# private_key_file should be in .env or github secrets
