# Not fully implemented yet. Please use with caution and veryify.

[esi]
user_agent = "wcmkts_backend/2.1dev, orthel.toralen@gmail.com, (https://github.com/OrthelT/wcmkts_backend)" #change this to reflect your app please.
compatibility_date = "2025-08-26"

[auth]
# esi_client_id, esi_secret_key, and refresh token should be set in .env file for local development. Use secure credential storage (github secrets) in production.
callback_url = "http://localhost:8000/callback"
token_file = "file:token.json"

[app]
name = "WinterCo Markets"
environment = "development"  # "production" or "development"
log_level = "info"

[db] # change this to reflect your database. You will need to also edit the database aliases in the .env file and in the .github/workflows/market-data-collection.yml file.
production_database_alias = "wcmktprod"
production_database_file = "wcmktprod.db"

testing_database_alias = "wcmkttest"
testing_database_file = "wcmkttest.db"

# North market (secondary production) database
deployment_database_alias = "wcmktnorth"
deployment_database_file = "wcmktnorth2.db"

[market_data]
primary_region_id = 10000003
deployment_region_id = 10000023

primary_system_id = 30000240
deployment_system_id = 30002029

primary_structure_id = 1035466617946
deployment_structure_id = 1046831245129

primary_market_name = "4-HWWF Keepstar"
deployment_market_name = "B-9C24 Keepstar"

[google_sheets]
enabled = true
sheet_url = 'https://docs.google.com/spreadsheets/d/1RmNJB9Yz4lG6kKKitGQ0zDuPbOiSe0ywn4SbSKabdwc/edit?gid=0#gid=0'
sheet_url2 = 'https://docs.google.com/spreadsheets/d/1sLr5VaUsHKfwZV_CA1K1o2bfywwzl4w-FGYWVnKmwKA/edit?gid=1670971557#gid=1670971557'
# private_key_file should be in .env or github secrets
